export const FETCH_CAPTIONS = "FETCH_CAPTIONS";
export const FETCH_TAGS = "FETCH_TAGS";
export const ADDING_TAG_TO_CAPTION_START = "ADDING_TAG_TO_CAPTION";
export const ADDING_TAG_TO_CAPTION_FAILURE = "ADDING_TAG_TO_CAPTION";
export const ADDING_TAG_TO_CAPTION_SUCCESS = "ADDING_TAG_TO_CAPTION";
